/* eslint-disable @next/next/no-sync-scripts */
import Head from 'next/head'
import Logo from "public/images/logo.png"

export default function head(){
    return (
        <Head>
            <title>I Fratelli</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
            <link rel="shortcut icon" type="link" href="images/logo.png" />
        </Head>
    )
}